version: "3"

services:
  prometheus:
    image: bitnami/prometheus
    container_name: java-tribe-software-contest-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=30d'
      - '--web.enable-admin-api'
    user: 0:0
    ports:
      - 9090:9090
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts/:/etc/prometheus/rules.d/
      - ./data/:/prometheus