version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: iclub-elasticsearch
    environment:
      - "cluster.name=iclubes" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9003:9200