version: "3"

services:
  tocmat:
    image: tomcat:8.0
    container_name: tomcat
    privileged: true
    ports:
      - '8081:8080'
    volumes:
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml

